### ISSUE TITLE
proposition de travailler en pull request 

### ISSUE THREAD

**Issue by JulienGenoud** [BJTUNourriture/Nourriture#1]
Je propose qu'on désigne deux masters pour les 3 parties,
– Serveur (Julian et Sylvain)
– Android (Julien et Maxime)
– Front (Benjamin et Valentin) 

et qu'on travaille uniquement en pull request cela permet:
– Être sur de garder une bonne structure globale du code que tout le monde ne push pas à n'importe quand.
– Une verification du code

bien sur ça n'empêche en rien à tout le monde de travailler sur toutes les parties,
ça désigne juste deux personne qui garantissent la review et la qualité du travail.

pour le fonctionnement c'est très simple 
-  je veux créer une feature 
- je crée une branche
- je fais un pull request sur la branche courante -> API, ANDROID ou Front
- le master peux accepter le pull request et modifier au besoin, ou refuser
- le master push sur la branche courante.

voilà.

**Comment by oborotev** [comment]
C'est pas une mauvaise idée dans l'ensemble, mais ce n'est pas utile pour ce projet. Il faut que tout le monde bosse sur toutes les parties, et les pull request vont etres plus embetantes qu'autre choses. On est une equipe de 6, et on est tous présents au même endroit. De plus on travaille en agile, et un des mottos de l'agile est de privilégier la communication. Donc pour des problèmes de structure de code ou autre, on communique entre nous. Aussi, nous devons mettre en place des tests unitaires, qui vont vérifier la qualité du travail. Je ne suis donc pas ok pour les pull requests.

**Comment by JulienGenoud** [comment]
Le système des pull request n'a jamais été incompatible ni avec les petites team,
ni avec le dev agile...,  c'est surtout un agrégat qui me permet de ne pas casser une partie du code de tel ou tel personne.

Mais bon je comprends ton point de vue.

**Comment by oborotev** [comment]
Non mais on est à coter quoi x) Et il y a des associations un peu bancale, je sais pas comment benjamin et valentin pourraient juger de la qualité du code angular en front, sachant qu'ils n'en ont pas encore fait ou peu..

**Comment by JulienGenoud** [comment]
Ben je vois pas pourquoi ils n'en serait pas capable,
vous n'aviez pas touché au nodeJS non plus avant ...
