### ISSUE TITLE
nodemailer error when timeout

### ISSUE THREAD

**Issue by JulienGenoud** [BJTUNourriture/Nourriture#12]
if nodemailer can' t send email the server crash with the following response : 

{ [Error: Connection timeout] code: 'ETIMEDOUT' }
.../server/API/controllers/users.js:269
            console.log("Message sent" + info.response);
                                             ^
TypeError: Cannot read property 'response' of undefined

**Comment by oborotev** [comment]
Added error handling if timeout.
